# Generated by Django 4.1 on 2022-08-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appVacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startmodel',
            name='start_fields',
            field=models.TextField(default='dsfsdsdf'),
        ),
    ]
